In [1]:
import pandas as pd
from flask import Flask
df1 = pd.read_csv('/home/mortal/python/project/Media_dashboard/data/raw/amazon_prime_titles.csv')
df2 = pd.read_csv('/home/mortal/python/project/Media_dashboard/data/raw/disney_plus_titles.csv')
df3 = pd.read_csv('/home/mortal/python/project/Media_dashboard/data/raw/hulu_titles.csv')
df4 = pd.read_csv('/home/mortal/python/project/Media_dashboard/data/raw/netflix_titles.csv')

df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   str
 1   type          9668 non-null   str
 2   title         9668 non-null   str
 3   director      7585 non-null   str
 4   cast          8435 non-null   str
 5   country       672 non-null    str
 6   date_added    155 non-null    str
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   str
 9   duration      9668 non-null   str
 10  listed_in     9668 non-null   str
 11  description   9668 non-null   str
dtypes: int64(1), str(11)
memory usage: 906.5 KB

/home/mortal/.local/lib/python3.12/site-packages/pandas/core/computation/expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.9.0' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/mortal/.local/lib/python3.12/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       1450 non-null   str
 1   type          1450 non-null   str
 2   title         1450 non-null   str
 3   director      977 non-null    str
 4   cast          1260 non-null   str
 5   country       1231 non-null   str
 6   date_added    1447 non-null   str
 7   release_year  1450 non-null   int64
 8   rating        1447 non-null   str
 9   duration      1450 non-null   str
 10  listed_in     1450 non-null   str
 11  description   1450 non-null   str
dtypes: int64(1), str(11)
memory usage: 136.1 KB

In [3]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 3073 entries, 0 to 3072
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       3073 non-null   str
 1   type          3073 non-null   str
 2   title         3073 non-null   str
 3   director      3 non-null      str
 4   cast          0 non-null      float64
 5   country       1620 non-null   str
 6   date_added    3045 non-null   str
 7   release_year  3073 non-null   int64
 8   rating        2553 non-null   str
 9   duration      2594 non-null   str
 10  listed_in     3073 non-null   str
 11  description   3069 non-null   str
dtypes: float64(1), int64(1), str(10)
memory usage: 288.2 KB

In [4]:
df4.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [5]:
df1

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...
9663,s9664,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",NaN,NaN,1940,7+,60 min,Comedy,New York City street principles get an East Si...
9664,s9665,TV Show,Planet Patrol,NaN,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",NaN,NaN,2018,13+,4 Seasons,TV Shows,"This is Earth, 2100AD - and these are the adve..."
9665,s9666,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",NaN,NaN,2008,R,90 min,Action,"In war-torn Eastern Europe, a world-weary grou..."
9666,s9667,TV Show,Maradona: Blessed Dream,NaN,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",NaN,NaN,2021,TV-MA,1 Season,"Drama, Sports","The series tells the story of Diego Maradona, ..."
9667,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w..."

In [6]:
df1['platfrom'] = 'Amazon Prime'
df2['platfrom'] = 'Disney Plus'
df3['platfrom'] = 'Hulu'
df4['platfrom'] = 'Netflix'
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   str
 1   type          9668 non-null   str
 2   title         9668 non-null   str
 3   director      7585 non-null   str
 4   cast          8435 non-null   str
 5   country       672 non-null    str
 6   date_added    155 non-null    str
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   str
 9   duration      9668 non-null   str
 10  listed_in     9668 non-null   str
 11  description   9668 non-null   str
 12  platfrom      9668 non-null   str
dtypes: int64(1), str(12)
memory usage: 982.0 KB

In [7]:
df = pd.concat([df1, df2, df3, df4], ignore_index= True)
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,platfrom
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...,Amazon Prime
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,Amazon Prime
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Amazon Prime
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ...",Amazon Prime
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,Amazon Prime
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",Netflix
22994,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",Netflix
22995,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,Netflix
22996,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",Netflix
22997,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Netflix

In [8]:
df = df.rename(columns={'platfrom': 'platform'})

In [9]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,platform
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...,Amazon Prime
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,Amazon Prime
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Amazon Prime
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ...",Amazon Prime
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,Amazon Prime
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",Netflix
22994,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",Netflix
22995,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,Netflix
22996,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",Netflix
22997,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Netflix

In [10]:
# Danh sách các cột dạng văn bản
text_cols = ['director', 'cast', 'country', 'rating', 'type', 'title', 'listed_in', 'description']

# Strip khoảng trắng và điền 'Unknown' cho giá trị NaN/rỗng
for col in text_cols:
    df[col] = df[col].fillna('Unknown').astype(str).str.strip()
    df[col] = df[col].replace({'nan': 'Unknown', '': 'Unknown'})

In [11]:
# Chuyển về định dạng datetime
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

# Điền các ô NaT bằng ngày 01/01 của năm phát hành
missing_dates = df['date_added'].isna()
df.loc[missing_dates, 'date_added'] = pd.to_datetime(
    df.loc[missing_dates, 'release_year'].astype(str) + '-01-01'
)

In [12]:
# Tách phần số (duration_int) và phần đơn vị (duration_unit)
df['duration_int'] = df['duration'].str.extract(r'(\d+)').astype(float)
df['duration_unit'] = df['duration'].str.extract(r'([a-zA-Z]+)')

In [13]:
# Xóa các dòng bị lặp lại dữ liệu
df = df.drop_duplicates()

# Kiểm tra lại cấu trúc dữ liệu sau khi làm sạch
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22998 entries, 0 to 22997
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   show_id        22998 non-null  str
 1   type           22998 non-null  str
 2   title          22998 non-null  str
 3   director       22998 non-null  str
 4   cast           22998 non-null  str
 5   country        22998 non-null  str
 6   date_added     22998 non-null  datetime64[us]
 7   release_year   22998 non-null  int64
 8   rating         22998 non-null  str
 9   duration       22516 non-null  str
 10  listed_in      22998 non-null  str
 11  description    22998 non-null  str
 12  platform       22998 non-null  str
 13  duration_int   22516 non-null  float64
 14  duration_unit  22516 non-null  str
dtypes: datetime64[us](1), float64(1), int64(1), str(12)
memory usage: 2.6 MB

In [15]:
# Xóa tất cả ký tự xuống dòng ẩn trong các cột chuỗi
for col in df.select_dtypes(include=['object', 'string']).columns:
    df[col] = df[col].astype(str).str.replace(r'[\r\n\u2028\u2029]', ' ', regex=True)

# Xuất lại file CSV mới
df.to_csv('/home/mortal/python/project/Media_dashboard/data/processed/final_cleaned.csv', index=False)